In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Durazno,51.1786,49.6769,32.67,99,100,3.04,RU,2021-04-03 15:27:45
1,1,Durazno,-28.7830,32.0377,71.71,69,86,14.05,ZA,2021-04-03 15:27:46
2,2,Durazno,-33.6971,-53.4616,74.62,53,49,8.08,UY,2021-04-03 15:27:46
3,3,Durazno,42.6001,-73.9662,42.01,21,0,8.72,US,2021-04-03 15:24:40
4,4,Durazno,19.7297,-155.0900,68.00,83,75,3.96,US,2021-04-03 15:22:49

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
Country        object
Date           object
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [6]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
#heat_layer = gmaps.heatmap_layer(locations, weights=temps)
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of humidity
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
humidity = city_data_df["Humidity"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
#heat_layer = gmaps.heatmap_layer(locations, weights=temps)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of cloudiness
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
cloudiness = city_data_df["Cloudiness"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
#heat_layer = gmaps.heatmap_layer(locations, weights=temps)
heat_layer = gmaps.heatmap_layer(locations, weights=cloudiness, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of Wind Speed
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
windspeed = city_data_df["Wind Speed"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
#heat_layer = gmaps.heatmap_layer(locations, weights=temps)
heat_layer = gmaps.heatmap_layer(locations, weights=windspeed, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [11]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
10,10,Durazno,-21.2078,-159.7750,78.80,83,40,4.61,CK,2021-04-03 15:27:49
11,11,Durazno,-2.0226,147.2712,78.91,86,100,7.07,PG,2021-04-03 15:27:49
12,12,Durazno,14.8961,-24.4956,76.32,61,17,6.87,CV,2021-04-03 15:27:19
17,17,Durazno,10.7670,75.9252,84.20,70,40,3.44,IN,2021-04-03 15:27:51
19,19,Durazno,-33.9258,18.4232,80.01,31,0,6.91,ZA,2021-04-03 15:25:43
24,24,Durazno,-6.6447,-51.9950,87.15,58,50,3.11,BR,2021-04-03 15:27:36
30,30,Durazno,22.2855,114.1577,79.00,69,9,4.43,HK,2021-04-03 15:27:11
35,35,Durazno,-19.8436,34.8389,84.00,61,20,6.91,MZ,2021-04-03 15:27:59
38,38,Durazno,-0.7393,-90.3518,80.60,78,20,9.22,EC,2021-04-03 15:28:01
40,40,Durazno,-22.9661,-42.0278,82.40,69,20,6.91,BR,2021-04-03 15:28:01

In [12]:
preferred_cities_df.count()

City_ID       196
City          196
Lat           196
Lng           196
Max Temp      196
Humidity      196
Cloudiness    196
Wind Speed    196
Country       194
Date          196
dtype: int64

In [13]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

       City Country  Max Temp      Lat       Lng Hotel Name
10  Durazno      CK     78.80 -21.2078 -159.7750
11  Durazno      PG     78.91  -2.0226  147.2712
12  Durazno      CV     76.32  14.8961  -24.4956
17  Durazno      IN     84.20  10.7670   75.9252
19  Durazno      ZA     80.01 -33.9258   18.4232
24  Durazno      BR     87.15  -6.6447  -51.9950
30  Durazno      HK     79.00  22.2855  114.1577
35  Durazno      MZ     84.00 -19.8436   34.8389
38  Durazno      EC     80.60  -0.7393  -90.3518
40  Durazno      BR     82.40 -22.9661  -42.0278

In [14]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping")

Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping

In [15]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
10,Durazno,CK,78.80,-21.2078,-159.7750,Paradise Inn
11,Durazno,PG,78.91,-2.0226,147.2712,Lorengau Harbourside Hotel
12,Durazno,CV,76.32,14.8961,-24.4956,Tortuga B&B
17,Durazno,IN,84.20,10.7670,75.9252,Rouba Residency
19,Durazno,ZA,80.01,-33.9258,18.4232,Southern Sun Waterfront Cape Town
24,Durazno,BR,87.15,-6.6447,-51.9950,Rio Xingu Camping
30,Durazno,HK,79.00,22.2855,114.1577,Mini Hotel Central
35,Durazno,MZ,84.00,-19.8436,34.8389,Beira Terrace Hotel
38,Durazno,EC,80.60,-0.7393,-90.3518,Finch Bay Galapagos Hotel
40,Durazno,BR,82.40,-22.9661,-42.0278,Pousada Porto Praia

In [16]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

NameError: name 'info_box_template' is not defined

In [18]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

NameError: name 'hotel_info' is not defined